---
title: "Modern M&A - Version Control - Using Git"
subtitle: "⚔<br/>with xaringan"
author: "The Authors Names ... just meta-data"
date: "2019/08/16 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    seal: false
    css: [theme/src/css/kunoichi.css,       theme/src/css/ninjutsu.css,
          theme/src/css/ninpo.css,          theme/src/css/default.css,
          theme/src/css/default-fonts.css,  theme/src/css/custom-fonts.css,
          theme/usr/css/custom.css,         assets/css/deck.css]
    chakra: theme/src/js/remark.min.js
    lib_dir: libs
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      navigation:
        scroll: false
    anchor_sections: false
    includes:
      after_body: [theme/usr/js/alt-title.html, theme/usr/js/tile-view-toggle.html]
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
xaringanExtra::use_tile_view()
knitr::opts_chunk$set(fig.path = "assets/img/")
```

```{asis notes, include=FALSE}
# NOTES:
```

```{r child="slides/theme.Rmd"}
```

---
```{r child="slides/1-title.Rmd"}
```

---
```{r child="slides/theme-series.Rmd"}
```

---
```{r child="slides/2-what-is-vc.Rmd"}
```

---
```{r child="slides/3-preface.Rmd"}
```

---
```{r child="slides/4-title-setup.Rmd"}
```

---
```{r child="slides/5-git-and-friends.Rmd"}
```

---
```{r child="slides/6-ssh-keys.Rmd"}
```

---
```{r child="slides/7-ssh-config.Rmd"}
```

---
```{r child="slides/8-git-config.Rmd"}
```

---
```{r child="slides/9-getting-started.Rmd"}
```
???
Demo by creating a new repo.
Then, delete it.
---
```{r child="slides/10-rproject-rstudio-git.Rmd"}
```
???
Demo with https://esgovcloud.com/mAndA/clone-me.
---
```{r child="slides/11-title-concepts-commands.Rmd"}
```

---
```{r child="slides/12-three-trees.Rmd"}
```

---
```{r child="slides/13-git-init.Rmd"}
```

---
```{r child="slides/14-git-add.Rmd"}
```

---
```{r child="slides/15-git-commit.Rmd"}
```

---
```{r child="slides/16-git-pull.Rmd"}
```

---
```{r child="slides/17-git-push.Rmd"}
```

---
```{r child="slides/18-title-undoing-things.Rmd"}
```

---
```{r child="slides/19-git-reset.Rmd"}
```

---
```{r child="slides/20-git-revert.Rmd"}
```

---
```{r child="slides/21-git-rm.Rmd"}
```

---
```{r child="slides/22-title-development-operations.Rmd"}
```

---
```{r child="slides/23-branching.Rmd"}
```

---
```{r child="slides/24-git-checkout.Rmd"}
```

---
```{r child="slides/25-releases.Rmd"}
```

---
```{r child="slides/26-git-tag.Rmd"}
```

---
```{r child="slides/27-title-large-files.Rmd"}
```

---
```{r child="slides/28-s3-git-lfs.Rmd"}
```

---
```{r child="slides/29-extras-aliases.Rmd"}
```

---
```{r child="slides/30-title-project-template.Rmd"}
```

---
```{r child="slides/31-project-template.Rmd"}
```

---
```{r child="slides/32-title-git-or-done.Rmd"}
```

---
```{r child="slides/resources.Rmd"}
```
