name: resources
class: nomargin-ul nomargin-h2 nomargin-h3 nomargin-h4 nopadding-h2 split-7

.row[
## <center>Presentation Resources</center>
]
.row[
.split-three[

.column.center[
### [Setup](#3)
#### [Friends of Git](#4)
Windows
- [Git for Windows](https://gitforwindows.org)
- [Terminal Emulator](https://esgovcloud.com/mAndA/savi/blob/master/CONTRIBUTING.md#windows-10)
- [chocolatey](https://chocolatey.org), [scoop](https://scoop.sh), [winget](https://github.com/microsoft/winget-cli)

macOS
- [Homebrew](https://brew.sh)
- [iTerm2](https://www.iterm2.com/index.html)

#### [SSH Keys](#5)
- [Connecting to GitHub with SSH](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh)
- [GitLab and SSH keys](https://docs.gitlab.com/ee/ssh/README.html)

#### [Getting Started](#9)
- [Demo Repo to Clone](https://esgovcloud.com/mAndA/clone-me)

#### [R Project + RStudio + Git](#10)
- [Using Projects in R / RStudio](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects)

#### [CLI, Aliases, & Extras](#29)
- [Oh My Zsh Git Plugin Aliases](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git)
- [Git Extras](https://github.com/tj/git-extras)
- [GitHub CLI](https://cli.github.com)
- [GitLab CLI](https://glab.readthedocs.io)
]

.column.center[
### Concepts
- [gitignore](https://git-scm.com/docs/gitignore)
- [merge conflicts](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#_basic_merge_conflicts)

#### [3 Trees of Git](#12)
- [Git Reset / 3 Trees](https://www.atlassian.com/git/tutorials/undoing-changes/git-reset)

#### [Revision Selection](#19)
- [man gitrevisions](https://git-scm.com/docs/gitrevisions)
- [Git Tools - Revision Selection](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection)

#### [Branching](#23)
- [Git Branching in a Nutshell](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell)

#### [Releases](#25)
- [Git Basics Tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging)
- [GitHub - Managing Releases](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository)
- [GitLab](https://docs.gitlab.com/ee/user/project/releases/index.html)

CI/CD Pipelines
- [GitLab CI/CD](https://docs.gitlab.com/ee/ci/), [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions), [Jenkins](https://jenkins.io), [AWS Codepipeline](https://aws.amazon.com/codepipeline/), [Travis CI](https://travis-ci.org/)

#### [Large Files](#28)
- [AWS CLI Install / Config](https://esgovcloud.com/mAndA/dev-docs/wiki/AWS-CLI)
- [Git Large File Storage](https://git-lfs.github.com/)


### Guides / Resources
- [Git the Simple Guide](http://rogerdudler.github.io/git-guide/)
]

.column.center[
### Git Commands
- [git status](https://git-scm.com/docs/git-status)
- [git clone](https://git-scm.com/docs/git-clone)
- [git init](https://git-scm.com/docs/git-init)
- [git remote](https://git-scm.com/docs/git-remote)
- [git add](https://git-scm.com/docs/git-add)
- [git commit](https://git-scm.com/docs/git-commit)
- [git log](https://git-scm.com/docs/git-log)
- [git pull](https://git-scm.com/docs/git-pull)
- [git push](https://git-scm.com/docs/git-push)
- [git reset](https://git-scm.com/docs/git-reset)
- [git revert](https://git-scm.com/docs/git-revert)
- [git rm](https://git-scm.com/docs/git-rm)
- [git branch](https://git-scm.com/docs/git-branch)
- [git checkout](https://git-scm.com/docs/git-checkout)
- [git merge](https://git-scm.com/docs/git-merge)
- [git tag](https://git-scm.com/docs/git-tag)
- [git lfs](https://github.com/git-lfs/git-lfs/tree/master/docs)
]
]]